//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcApi.Properties.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple actions were found that match the request: {0}.
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on type {1}.
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatchType {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action was found on the controller &apos;{0}&apos; that matches the name &apos;{1}&apos;..
        /// </summary>
        internal static string ApiControllerActionSelector_ActionNameNotFound {
            get {
                return ResourceManager.GetString("ApiControllerActionSelector_ActionNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action was found on the controller &apos;{0}&apos; that matches the request..
        /// </summary>
        internal static string ApiControllerActionSelector_ActionNotFound {
            get {
                return ResourceManager.GetString("ApiControllerActionSelector_ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple actions were found that match the request: {0}.
        /// </summary>
        internal static string ApiControllerActionSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ApiControllerActionSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource does not support http method &apos;{0}&apos;..
        /// </summary>
        internal static string ApiControllerActionSelector_HttpMethodNotSupported {
            get {
                return ResourceManager.GetString("ApiControllerActionSelector_HttpMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        internal static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to {0}..
        /// </summary>
        internal static string ArgumentMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IAsyncResult has already been consumed..
        /// </summary>
        internal static string AsyncCommon_AsyncResultAlreadyConsumed {
            get {
                return ResourceManager.GetString("AsyncCommon_AsyncResultAlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IAsyncResult is not valid for this method..
        /// </summary>
        internal static string AsyncCommon_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string CannotHaveNullInList {
            get {
                return ResourceManager.GetString("CannotHaveNullInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; of &apos;{1}&apos; cannot be used as a supported media type because it is a media range..
        /// </summary>
        internal static string CannotUseMediaRangeForSupportedMediaType {
            get {
                return ResourceManager.GetString("CannotUseMediaRangeForSupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must derive from {1}..
        /// </summary>
        internal static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service type {0} is not supported..
        /// </summary>
        internal static string DefaultServices_InvalidServiceType {
            get {
                return ResourceManager.GetString("DefaultServices_InvalidServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string DependencyResolverNoService {
            get {
                return ResourceManager.GetString("DependencyResolverNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the HTTP method is invalid..
        /// </summary>
        internal static string HttpMethodFormatError {
            get {
                return ResourceManager.GetString("HttpMethodFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason phrase must not contain new-line characters..
        /// </summary>
        internal static string HttpStatusDescriptionFormatError {
            get {
                return ResourceManager.GetString("HttpStatusDescriptionFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid media range..
        /// </summary>
        internal static string InvalidMediaRange {
            get {
                return ResourceManager.GetString("InvalidMediaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error/{0}] {1}.
        /// </summary>
        internal static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Fatal/{0}] {1}.
        /// </summary>
        internal static string LogFatal {
            get {
                return ResourceManager.GetString("LogFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info/{0}] {1}.
        /// </summary>
        internal static string LogInfo {
            get {
                return ResourceManager.GetString("LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warn/{0}] {1}.
        /// </summary>
        internal static string LogWarn {
            get {
                return ResourceManager.GetString("LogWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encoding found for media type formatter &apos;{0}&apos;. There must be at least one supported encoding registered in order for the media type formatter to read or write content..
        /// </summary>
        internal static string MediaTypeFormatterNoEncoding {
            get {
                return ResourceManager.GetString("MediaTypeFormatterNoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be set before &apos;{1}&apos; can serialize its content..
        /// </summary>
        internal static string MediaTypeMustBeSetBeforeWrite {
            get {
                return ResourceManager.GetString("MediaTypeMustBeSetBeforeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-null request URI must be provided to determine if a &apos;{0}&apos; matches a given request or response message..
        /// </summary>
        internal static string NonNullUriRequiredForMediaTypeMapping {
            get {
                return ResourceManager.GetString("NonNullUriRequiredForMediaTypeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; is available to write an object of type &apos;{1}&apos; with the media type &apos;{2}&apos;..
        /// </summary>
        internal static string NoWriteSerializerAvailable {
            get {
                return ResourceManager.GetString("NoWriteSerializerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error in {0}. {1}.
        /// </summary>
        internal static string ParseErrorInClause {
            get {
                return ResourceManager.GetString("ParseErrorInClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData query parameter &apos;{0}&apos; has an invalid value. The value should be a positive integer. The provided value was &apos;{1}&apos;.
        /// </summary>
        internal static string PositiveIntegerExpectedForODataQueryParameter {
            get {
                return ResourceManager.GetString("PositiveIntegerExpectedForODataQueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Media Type: &apos;{0}&apos;..
        /// </summary>
        internal static string Resources_UnsupportedMediaType {
            get {
                return ResourceManager.GetString("Resources_UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; &apos;{1}&apos; parameter must have a reference to a &apos;{2}&apos; via the &apos;{3}&apos; property..
        /// </summary>
        internal static string ResponseMustReferenceRequest {
            get {
                return ResourceManager.GetString("ResponseMustReferenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultLimitAttribute cannot be applied to a non ReflectedActionDescriptor type..
        /// </summary>
        internal static string ResultLimitFilter_InvalidActionDescriptor {
            get {
                return ResourceManager.GetString("ResultLimitFilter_InvalidActionDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultLimitAttribute cannot be applied to action &apos;{0}&apos; because it&apos;s return type is not IEnumerable..
        /// </summary>
        internal static string ResultLimitFilter_InvalidReturnType {
            get {
                return ResourceManager.GetString("ResultLimitFilter_InvalidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit specified by the ResultLimitAttribute applied to action &apos;{0}&apos; must be greater than zero..
        /// </summary>
        internal static string ResultLimitFilter_OutOfRange {
            get {
                return ResourceManager.GetString("ResultLimitFilter_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; serializer cannot serialize the type &apos;{1}&apos;..
        /// </summary>
        internal static string SerializerCannotSerializeType {
            get {
                return ResourceManager.GetString("SerializerCannotSerializeType", resourceCulture);
            }
        }
    }
}
